#!/usr/bin/env python3
"""Generates src/synth_lut.rs from the SynthLUT_FDD/SynthLUT_TDD tables in the no-OS ad9361.c.

Usage: tools/gen_ad9361_synth_lut.py [path/to/ad9361.c] > src/synth_lut.rs
"""
import re
import sys

from adi_notice import rust_notice

SRC = sys.argv[1] if len(sys.argv) > 1 else \
    "../no-OS/drivers/rf-transceiver/ad9361/ad9361.c"
text = open(SRC, encoding="utf-8", errors="replace").read()
FIELDS = ["vco_mhz", "vco_output_level", "vco_varactor", "vco_bias_ref", "vco_bias_tcf",
          "vco_cal_offset", "vco_varactor_reference", "charge_pump_current", "lf_c2", "lf_c1",
          "lf_r1", "lf_c3", "lf_r3"]
SIZE = 53


def table(name):
    m = re.search(r"static const struct SynthLUT %s\[LUT_FTDD_ENT\]\[SYNTH_LUT_SIZE\] = \{(.*?)\n\};" % name,
                  text, re.S)
    rows = re.findall(r"\{\s*(\d+(?:\s*,\s*\d+){12})\s*\}", m.group(1))
    rows = [[int(v) for v in r.split(",")] for r in rows]
    assert len(rows) == 3 * SIZE, (name, len(rows))
    return [rows[i * SIZE:(i + 1) * SIZE] for i in range(3)]


print(rust_notice("Copyright 2014-2015(c) Analog Devices, Inc. (drivers/rf-transceiver/ad9361/ad9361.c)"))
print("""//! AD9361 RF synthesizer VCO/loop filter lookup tables.
//!
//! GENERATED by `tools/gen_ad9361_synth_lut.py` from the no-OS `ad9361.c` tables -- regenerate
//! instead of editing by hand.

/// Number of entries per table.
pub const SYNTH_LUT_SIZE: usize = %d;

/// One VCO frequency step of a synthesizer lookup table.
#[derive(Clone, Copy, Debug)]
pub struct SynthLut {""" % SIZE)
for f in FIELDS:
    print(f"    pub {f}: {'u16' if f == 'vco_mhz' else 'u8'},")
print("}\n")
print("""/// Table for each reference clock range: below 50 MHz, up to 70 MHz, and above.
pub type SynthLutSet = [[SynthLut; SYNTH_LUT_SIZE]; 3];
""")
for name, const in (("SynthLUT_FDD", "SYNTH_LUT_FDD"), ("SynthLUT_TDD", "SYNTH_LUT_TDD")):
    print(f"pub static {const}: SynthLutSet = [")
    for block in table(name):
        print("    [")
        for r in block:
            print("        SynthLut { " + ", ".join(f"{f}: {v}" for f, v in zip(FIELDS, r)) + " },")
        print("    ],")
    print("];\n")
