#!/usr/bin/env python3
"""Generates src/gain_tables.rs from the RX gain tables in the no-OS ad9361.c.

Usage: tools/gen_ad9361_gain_tables.py [path/to/ad9361.c] > src/gain_tables.rs
"""
import re
import sys

from adi_notice import rust_notice

SRC = sys.argv[1] if len(sys.argv) > 1 else \
    "../no-OS/drivers/rf-transceiver/ad9361/ad9361.c"
text = open(SRC, encoding="utf-8", errors="replace").read()


def array(name, size, abs_gain):
    m = re.search(r"static const %s\s+%s\[RXGAIN_TBLS_END\]\[SIZE_\w+_TABLE\](?:\[3\])?\s*=\s*\{(.*?)\n\};" %
                  ("int8_t" if abs_gain else "uint8_t", name), text, re.S)
    body = m.group(1)
    if abs_gain:
        tables = re.split(r"\}\s*,\s*\{", body)
        out = [[int(v) for v in re.findall(r"-?\d+", re.sub(r"/\*.*?\*/", "", t))] for t in tables]
    else:
        vals = [int(v, 16) for v in re.findall(r"0x[0-9A-Fa-f]+", body)]
        assert len(vals) == 3 * 3 * size, (name, len(vals))
        rows = [vals[i:i + 3] for i in range(0, len(vals), 3)]
        out = [rows[i * size:(i + 1) * size] for i in range(3)]
    assert len(out) == 3 and all(len(t) == size for t in out), (name, [len(t) for t in out])
    return out


FULL, SPLIT = 77, 41
print(rust_notice("Copyright 2014-2015(c) Analog Devices, Inc. (drivers/rf-transceiver/ad9361/ad9361.c)"))
print("""//! AD9361 RX gain tables.
//!
//! GENERATED by `tools/gen_ad9361_gain_tables.py` from the no-OS `ad9361.c` tables -- regenerate
//! instead of editing by hand.

/// Entries of a full gain table.
const SIZE_FULL_TABLE: usize = %d;
/// Entries of a split gain table.
const SIZE_SPLIT_TABLE: usize = %d;

/// A gain table for a range of RX LO frequencies.
pub struct GainTable {
    /// Exclusive lower bound of the LO frequency range in Hz
    pub start: u64,
    /// Inclusive upper bound of the LO frequency range in Hz
    pub end: u64,
    pub split_table: bool,
    /// The three gain table words of each index
    pub entries: &'static [[u8; 3]],
    /// Absolute gain in dB of each index
    pub abs_gain: &'static [i8],
}
""" % (FULL, SPLIT))


def emit(const, ty_words, ty_gain, words, gains, size):
    size_const = "SIZE_FULL_TABLE" if size == FULL else "SIZE_SPLIT_TABLE"
    print(f"const {const}: [[[u8; 3]; {size_const}]; 3] = [")
    for t in words:
        print("    [")
        for r in t:
            print("        [" + ", ".join(f"{v:#04x}" for v in r) + "],")
        print("    ],")
    print("];\n")
    print(f"const {const}_ABS_GAIN: [[i8; {size_const}]; 3] = [")
    for t in gains:
        print("    [" + ", ".join(str(v) for v in t) + "],")
    print("];\n")


emit("FULL_GAIN_TABLE", None, None, array("full_gain_table", FULL, False),
     array("full_gain_table_abs_gain", FULL, True), FULL)
emit("SPLIT_GAIN_TABLE", None, None, array("split_gain_table", SPLIT, False),
     array("split_gain_table_abs_gain", SPLIT, True), SPLIT)

print("/// All gain tables: full tables for 0-1.3 GHz, 1.3-4 GHz and 4-6 GHz, then the same for the")
print("/// split tables.")
print("pub static GAIN_TABLES: [GainTable; 6] = [")
ranges = [(0, 1_300_000_000), (1_300_000_000, 4_000_000_000), (4_000_000_000, 6_000_000_000)]
for prefix, split in (("FULL", False), ("SPLIT", True)):
    for i, (a, b) in enumerate(ranges):
        print(f"    GainTable {{ start: {a}, end: {b}, split_table: {str(split).lower()}, "
              f"entries: &{prefix}_GAIN_TABLE[{i}], abs_gain: &{prefix}_GAIN_TABLE_ABS_GAIN[{i}] }},")
print("];")
